export type HomeLanguage='zh'|'en';
export const journeyThemes=[
  {id:'milky-way',image:'/brand/milky-way-4096.webp',srcSet:'/brand/milky-way-1920.webp 1920w, /brand/milky-way-4096.webp 4096w, /brand/milky-way-6000.webp 6000w',name:{zh:'银河之中',en:'Within the Milky Way'},line:{zh:'让目光，驶向银河。',en:'Let your gaze drift into the galaxy.'},description:{zh:'从熟悉的星光出发，去银河的另一处看看。',en:'Begin beneath familiar stars. Discover how the sky changes elsewhere.'},credit:'ESO/S. Brunier',source:'https://www.eso.org/public/images/eso0932a/'},
  {id:'orion',image:'/brand/theme-orion.webp',srcSet:undefined,name:{zh:'星云深处',en:'Inside the nebula'},line:{zh:'穿过尘埃，遇见新生。',en:'Through the dust, new stars awaken.'},description:{zh:'在光与暗交织的云气中，看见恒星诞生的痕迹。',en:'Explore the light and shadow of a stellar nursery.'},credit:'ESO/G. Beccari',source:'https://www.eso.org/public/images/eso1723a/'},
  {id:'andromeda',image:'/brand/theme-andromeda.webp',srcSet:undefined,name:{zh:'银河之外',en:'Beyond our galaxy'},line:{zh:'越过星海，还有星海。',en:'Beyond one sea of stars, another.'},description:{zh:'把视线交给仙女座，让熟悉的天空通向更远处。',en:'Look toward Andromeda and let the familiar sky lead you farther.'},credit:'NASA, ESA, Digitized Sky Survey 2; Davide De Martin',source:'https://esahubble.org/images/heic1502b/'},
] as const;
export const featureSlides=[
  {theme:0,title:{zh:'换个位置，重看星空',en:'A new position. A different sky.'},body:{zh:'从预设坐标启程，或在银河位置图中自由选点。位置跳转会真正移动观察者；左侧方向按钮只改变朝向。',en:'Travel to a preset position or choose a point on the galactic map. Position controls move the observer; direction buttons only turn the view.'},detail:{zh:'太阳邻域 · 内银河 · 外盘 · 盘面上方',en:'Solar neighbourhood · Inner disc · Outer disc · Above the plane'}},
  {theme:1,title:{zh:'找到名字背后的星光',en:'Find the light behind a name.'},body:{zh:'输入中文名、英文名或已有星表编号，定位恒星、星云、星团与目录星系。也可以直接点选，查看资料与来源。',en:'Search by Chinese or English name, or a supported catalogue number. Select stars, nebulae, clusters and catalogued galaxies to inspect their data and sources.'},detail:{zh:'搜索天体 · 点击查看 · 真实来源',en:'Search objects · Select and inspect · Trace the source'}},
  {theme:0,title:{zh:'让漫长的时间流动',en:'Watch time unfold.'},body:{zh:'播放、暂停或反向推进模拟时间，观察天体与观察者的运动。打开中心锁定，移动时仍能始终看向银河中心。',en:'Play, pause or reverse simulated time. Watch stars and the observer move, or keep the view locked on the galactic centre throughout your journey.'},detail:{zh:'时间推进 · 轨道运动 · 持续中心锁定',en:'Time controls · Orbital motion · Centre tracking'}},
  {theme:2,title:{zh:'换一双眼睛，看向更远处',en:'See farther. See differently.'},body:{zh:'切换裸眼、暗适应或相机响应，调整晨昏与大气。银河之外也有可供寻找的天体；第一次进入时，可以跟随新手引导启航。',en:'Change between naked-eye, dark-adapted and camera responses, then explore twilight and atmospheric conditions. Look beyond the Milky Way, with a first-visit guide to help you begin.'},detail:{zh:'感光与大气 · 深空影像 · 新手引导',en:'Vision and atmosphere · Deep-sky images · Guided introduction'}},
] as const;
export function nextSlide(index:number,offset:number,count:number){return ((index+offset)%count+count)%count;}
